services:
    mafiascum.votecounter_extension.votecount_listener:
        class: mafiascum\votecounter_extension\event\votecount_listener
        arguments:
            - '@config'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '@dbal.conn'
            - '%core.php_ext%'
            - '@cache.driver'
        tags:
            - { name: event.listener }
